# Generated by Django 5.1 on 2024-08-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
    ]
