# Generated by Django 5.1 on 2024-08-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_work_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='users/covers/users/%Y/%m/%d'),
        ),
    ]
