# Generated by Django 5.1 on 2024-08-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_remove_customer_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, default='', null=True, upload_to='services/covers/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_time', models.DurationField()),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barbers', models.ManyToManyField(related_name='services', to='users.employee')),
            ],
        ),
    ]
