# Generated by Django 5.1 on 2024-08-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('users', '0009_remove_customer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='barbers',
            field=models.ManyToManyField(blank=True, related_name='services', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
