# Generated by Django 5.1 on 2024-08-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0009_remove_customer_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
