# Generated by Django 5.1 on 2024-08-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_service_barbers_alter_service_status'),
        ('users', '0009_remove_customer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.branch'),
        ),
    ]
