# Generated by Django 5.1 on 2024-08-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_branch'),
        ('users', '0009_remove_customer_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='barber',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
    ]
