# Generated by Django 5.1 on 2024-09-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_barber'),
        ('users', '0010_remove_employee_services_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.service'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_highlighted',
            field=models.BooleanField(db_comment='Highlight this service in the home page', default=False),
        ),
    ]
