# Generated by Django 5.1 on 2024-09-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservation_barber_alter_reservation_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
