# Generated by Django 5.1 on 2024-09-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taggeditem",
            old_name="name",
            new_name="tag",
        ),
    ]
